version: "3.3"
services:
  auth:
    container_name: auth
    build: auth/.
    networks:
      - app-network

  user:
    container_name: user
    build: user/.
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - database

  card:
    container_name: card
    build: card/.
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - database

  game:
    container_name: game
    build: game/.
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - database

  room:
    container_name: room
    build: room/.
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - database

  database:
    container_name: database
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    networks:
      - app-network
    ports:
    - "5433:5432"

  frontend:
      container_name: frontend
      image: nginx
      ports:
        - "8080:8080"
      environment:
        - NGINX_PORT=8080
      networks:
        - app-network
      volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf
      - ./data/website:/etc/nginx/html

networks:

  app-network:
