version: "3.2"
services:
  web:
    container_name: web
    build: Backend/.
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
    - "8080:8080"
    depends_on:
      - database

  database:
    container_name: database
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    networks:
      - app-network
networks:
  app-network:
