version: "3.3"
services:
  web:
    container_name: web
    build: Backend/.
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - database

  user:
    container_name: user
    build: user/.
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - database

  database:
    container_name: database
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    networks:
      - app-network

  frontend:
      container_name: frontend
      image: nginx
      ports:
        - "8080:8080"
      environment:
        - NGINX_PORT=8080
      networks:
        - app-network
      depends_on:
        - web
      volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf
      - ./data/website:/etc/nginx/html

networks:
  app-network:
